blog/urls.py
from django.urls import path
from . import views
from .views import PostDeleteView
app_name = 'blog'
urlpatterns = [
    path('',views.post_list,name = 'post_list'),
    path('post/<int:pk>/', views.post_detail,name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post_delete'),
]

bookmark/urls.py
from django.urls import path
from .views import BookmarkListView, BookmarkCreateView, \
    BookmarkDetailView, BookmarkUpdateView, BookmarkDeleteView

app_name = 'bookmark'
urlpatterns = [
    path('', BookmarkListView.as_view(), name = 'list'),
    path('add/', BookmarkCreateView.as_view(), name = 'add'),
    path('detail/<int:pk>/', BookmarkDetailView.as_view(), name = 'detail'),
    path('update/<int:pk>/', BookmarkUpdateView.as_view(), name = 'update'),
    path('delete/<int:pk>/', BookmarkDeleteView.as_view(), name = 'delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('polls/', include('polls.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns=[
    path('',views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name = 'detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name = 'results'),
    path('<int:question_id>/vote/', views.vote, name = 'vote'),
    path('resultlist/', views.result_list, name='result_list'),
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now()- datetime.timedelta(days=1)

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.template import loader
from django.views import generic
from .models import Question, Choice

# Create your views here.
def result_list(request):
    questions = Question.objects.order_by('pub_date')
    return render(request, 'polls/result_list.html',{'questions':questions})

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    #"""Return the last five published questions."""
    def get_queryset(self):
        return Question.objects.order_by('pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    #return HttpResponse("You're voting on question %s." % question_id)
    question = get_object_or_404(Question, pk = question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question':question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()

        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css'%}"
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
   <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">2005899 통합앱</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id ="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home<span class="sr-only">(current)</span> </a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'polls:index' %}">설문조사<span class="sr-only">(current)</span> </a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'bookmark:list' %}">북마크<span class="sr-only">(current)</span> </a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'blog:post_list' %}">블로그<span class="sr-only">(current)</span> </a>
                </li>
            </ul>
        </div>
    </nav>
    <p></p>
    <div class="row">
        <div class="col">
            {% block content %}
            {% endblock %}

            {% block pagination %}
            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

polls/templates/polls/detail.html
{% extends 'polls/base.html' %}
{% block content %}
<h1>{{question.question_text}}</h1>
{% if error_message %} <p><strong>{{error_message}}</strong></p> {% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
    <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br>
{% endfor %}
    <input type="submit" value="Vote">
</form>
{% endblock %}

polls/templates/polls/index.html
{% extends 'polls/base.html' %}
{% block content %}
    {% if latest_question_list %}
        <ul>
            {% for question in latest_question_list %}
                <li><a href = "{% url 'polls:detail' question.id %}">{{question.question_text}}</a></li>
            {% endfor %}
        </ul>
    <a href="{% url 'polls:result_list' %}" class="btn btn-info">설문조사 결과</a>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock %}

polls/templates/polls/result_list.html
{% extends 'polls/base.html' %}
{% block content %}
<h1>설문조사 결과 모음</h1>
<br>
    {% for question in questions %}
    <div class="post">
        <h2>{{question.question_text}}</h2>
        <ul>
            {% for choice in question.choice_set.all %}
        <li>{{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes|pluralize}}</li>
        {% endfor %}
        </ul>
        <hr>
    </div>
    {% endfor %}

{% endblock %}

polls/templates/polls/results.html
{% extends 'polls/base.html' %}
{% block content %}
  <h1>{{question.question_text}}</h1>
    <ul>
        {% for choice in question.choice_set.all %}
        <li>{{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes|pluralize}}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock %}